#!/usr/bin/env bash

help()
{
    cat "$(swd)/help/popcorn.txt"
}

scriptpath()
{
    result=${BASH_SOURCE[0]}

    # unfortunately readlink -f isn't available on Macs,
    # so resolve the symlinks manually
    while [ -h "$result" ]
    do
        symdir=$(dirname "$result")
        cd -P "$symdir"
        result=$(readlink "$result")
    done

    echo "$result"
}

swd()
{
    dirname "$(scriptpath)"
}

usage()
{
    help 1>&2
    exit 1
}

output=/dev/null
times=1

test $# -gt 0 || usage

while [ $# -gt 0 ]
do
    case "$1" in
        '-?'|-h|--help)
            help
            exit 0
            ;;
        -o|--output)
            shift
            output=$1
            ;;
        -t|--times)
            shift
            times=$1
            ;;
        *)
            package=$1
            ;;
    esac
    shift
done

test ! -z "$package" || usage

url=https://www.nuget.org/api/v2/package/$package
seq=$(seq 1 $times)

for i in $seq
do
    curl -sSLo "$output" "$url"
done
