#!/usr/bin/env bash

help()
{
}

usage()
{
    help 1>&2
    exit 1
}

output=/dev/null
times=1

test $# -gt 0 || usage

while [ $# -gt 0 ]
do
    case "$1" in
        '-?'|-h|--help)
            help
            exit 0
            ;;
        -o|--output)
            shift
            output=$1
            ;;
        -t|--times)
            shift
            times=$1
            ;;
        *)
            package=$1
            ;;
    esac
    shift
done

test ! -z "$package" || usage

url=https://www.nuget.org/api/v2/package/$package

for i in {1..$times}
do
    curl -sSLo "$output" "$url"
done
